from dstack._internal.core.error import DstackError


class CLIError(DstackError):
    pass
